//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportLoadXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public string CARDCODE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> FINISHDATE { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string SURNAME { get; set; }
        public string FULLNAME { get; set; }
        public byte GENDERID { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string PHONEHOME { get; set; }
        public string PHONEMOBIL { get; set; }
        public string EMAIL { get; set; }
        public string CITY { get; set; }
        public string STREET { get; set; }
        public Nullable<byte> HOUSE { get; set; }
        public Nullable<byte> APARTMENT { get; set; }
        public string ALTADDRESS { get; set; }
        public string CARDTYPE { get; set; }
        public System.Guid OWNERGUID { get; set; }
        public byte CARDPER { get; set; }
        public decimal TURNOVER { get; set; }
    }
}
