CREATE DATABASE TestDB;
GO
USE TestDB;
GO



CREATE TABLE ImportDataXML
(
	CARDCODE VARCHAR(11),
	STARTDATE DATETIME,
	FINISHDATE DATETIME,
	LASTNAME VARCHAR(20),
	FIRSTNAME  VARCHAR(15),
	SURNAME VARCHAR(15),
	FULLNAME VARCHAR(50),
	GENDERID TINYINT NOT NULL,
	BIRTHDAY DATETIME,
	PHONEHOME VARCHAR(11),
	PHONEMOBIL VARCHAR(15),
	EMAIL VARCHAR(20),
	CITY VARCHAR(20),
	STREET VARCHAR(50),
	HOUSE TINYINT,
	APARTMENT TINYINT,
	ALTADDRESS VARCHAR(50),
	CARDTYPE VARCHAR(50),
	OWNERGUID UNIQUEIDENTIFIER NOT NULL,
	CARDPER TINYINT NOT NULL,
	TURNOVER MONEY NOT NULL
	CONSTRAINT PK_ImportXML_CARDCODE PRIMARY KEY (CARDCODE),
	CONSTRAINT CK_ImportXML_STARTDATE CHECK (STARTDATE<FINISHDATE),
	CONSTRAINT CK_ImportXML_GENDERID CHECK (GENDERID BETWEEN 1 AND 3)
)



